package Forms.DB;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Kasun Dhananjaya
 */
import Blood_Bank.DatabaseConnection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class AAAWelcomePage extends javax.swing.JFrame {

    /**
     * Creates new form WelcomePage
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomePageProgressBar = new javax.swing.JProgressBar();
        lblProgressBarText = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomePageProgressBar.setStringPainted(true);
        getContentPane().add(welcomePageProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 880, 20));

        lblProgressBarText.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblProgressBarText.setText("Percentage%");
        getContentPane().add(lblProgressBarText, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 320, 30));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("WELCOME TO THE SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 819, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/kasun/Documents/JAVA Project/NewFolder/BloodBankSystem/src/Forms/Images/kasun.jpg")); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form WelcomePage
     */
    public AAAWelcomePage() {
        initComponents();
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    try {
                        
                        welcomePageProgressBar.setValue(i);
                        if (i > 30 && i < 70) {
                            lblProgressBarText.setText("Setting Up Interfaces");
                        } else if (i > 70) {
                            DatabaseConnection dbc =new DatabaseConnection() {};
                            dbc.databaseConnection();
                            dbc.closeDBcon();
                            lblProgressBarText.setText("Loading Databases");
                        } else {
                          FPage f = new FPage();
                            lblProgressBarText.setText("Loading started");
                        }
                        Thread.sleep(50);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(AAAWelcomePage.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(AAAWelcomePage.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(AAAWelcomePage.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (i == 100) {
                                FPage fp = new FPage();
                                fp.show();
        fp.show();
        dispose();
                    }
                }
            }
        });
        t.start();

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AAAWelcomePage().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblProgressBarText;
    private javax.swing.JProgressBar welcomePageProgressBar;
    // End of variables declaration//GEN-END:variables
}
