package Forms.DB;

import Blood_Bank.HgetBpacket;
import Blood_Bank.InsertAndRetriewAdvacedDD;
import Blood_Bank.ScanQr;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kasun Dhananjaya
 */
public class AdvancedDD extends javax.swing.JFrame {

    private Component frame;

    /**
     * Creates new form FormForDoner
     */
    public AdvancedDD() {
        initComponents();
        addError();
        SubmitBt.setEnabled(false);
        ResetBtn.setEnabled(false);
    }
    private String Bltype,LastDDate;
    private double height,weight;
    private boolean suspicious=false,sus;
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderBtn = new javax.swing.ButtonGroup();
        rootPanel1 = new javax.swing.JPanel();
        ResetBtn = new javax.swing.JToggleButton();
        BackBtn = new javax.swing.JToggleButton();
        BgPanel = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        containelPanel = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        BPID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        DID = new javax.swing.JTextField();
        Search = new javax.swing.JToggleButton();
        lblValidateDID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Btype = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        HeightTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        WeightTxt = new javax.swing.JTextField();
        lblValidateWeight = new javax.swing.JLabel();
        lblValidateHeight = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LastDT = new com.toedter.calendar.JDateChooser();
        sqr = new javax.swing.JToggleButton();
        LeftPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Bx1 = new javax.swing.JCheckBox();
        Bx3 = new javax.swing.JCheckBox();
        Bx5 = new javax.swing.JCheckBox();
        Bx7 = new javax.swing.JCheckBox();
        Bx4 = new javax.swing.JCheckBox();
        Bx6 = new javax.swing.JCheckBox();
        Bx8 = new javax.swing.JCheckBox();
        Bx2 = new javax.swing.JCheckBox();
        Bx10 = new javax.swing.JCheckBox();
        Bx11 = new javax.swing.JCheckBox();
        Bx9 = new javax.swing.JCheckBox();
        Bx12 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        SubmitBt = new javax.swing.JToggleButton();
        Header = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rootPanel1.setBackground(new java.awt.Color(153, 255, 255,35));

        ResetBtn.setText("Reset");

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanel1Layout = new javax.swing.GroupLayout(rootPanel1);
        rootPanel1.setLayout(rootPanel1Layout);
        rootPanel1Layout.setHorizontalGroup(
            rootPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanel1Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(290, Short.MAX_VALUE))
        );
        rootPanel1Layout.setVerticalGroup(
            rootPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(rootPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(rootPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 900, 120));

        BgPanel.setBackground(new java.awt.Color(153, 255, 255,35));
        BgPanel.setPreferredSize(new java.awt.Dimension(900, 750));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Donating Form");
        BgPanel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, -1, 50));

        containelPanel.setBackground(new java.awt.Color(0, 0, 0,35));

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("BPID");

        BPID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BPID.setText("BPID");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Dorner ID");

        DID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DIDMouseClicked(evt);
            }
        });
        DID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIDActionPerformed(evt);
            }
        });
        DID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DIDKeyReleased(evt);
            }
        });

        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        lblValidateDID.setFont(new java.awt.Font("Yu Gothic Light", 2, 14)); // NOI18N
        lblValidateDID.setText("Validate");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Blood Type");

        Btype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Height (cm)");

        HeightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightTxtActionPerformed(evt);
            }
        });
        HeightTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                HeightTxtKeyReleased(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Weight (kg)");

        WeightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTxtActionPerformed(evt);
            }
        });
        WeightTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WeightTxtKeyReleased(evt);
            }
        });

        lblValidateWeight.setFont(new java.awt.Font("Yu Gothic Light", 2, 14)); // NOI18N
        lblValidateWeight.setText("Validate");

        lblValidateHeight.setFont(new java.awt.Font("Yu Gothic Light", 2, 14)); // NOI18N
        lblValidateHeight.setText("Validate");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Last Time Donated ");

        LastDT.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                LastDTComponentAdded(evt);
            }
        });
        LastDT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LastDTMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LastDTMousePressed(evt);
            }
        });
        LastDT.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                LastDTInputMethodTextChanged(evt);
            }
        });
        LastDT.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                LastDTPropertyChange(evt);
            }
        });
        LastDT.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                LastDTVetoableChange(evt);
            }
        });

        sqr.setText("Scan Qr");
        sqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sqr, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel12))
                                .addGap(69, 69, 69)
                                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RightPanelLayout.createSequentialGroup()
                                        .addComponent(DID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Btype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(HeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValidateWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(WeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValidateHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblValidateDID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BPID)))
                            .addGroup(RightPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(LastDT, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPID)
                    .addComponent(jLabel12))
                .addGap(12, 12, 12)
                .addComponent(sqr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Search)
                        .addComponent(DID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidateDID)
                .addGap(20, 20, 20)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Btype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel10))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addComponent(HeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValidateHeight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WeightTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValidateWeight)))
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel7))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(LastDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Suspicious : ");

        Bx1.setText("Heart Diseases");

        Bx3.setText("Diabetes");

        Bx5.setText("Cancer");
        Bx5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bx5ActionPerformed(evt);
            }
        });

        Bx7.setText("Paralises");

        Bx4.setText("Lung Diseases");

        Bx6.setText("Blood Diseases");
        Bx6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bx6ActionPerformed(evt);
            }
        });

        Bx8.setText("Kidney Diseases");

        Bx2.setText("Liver Diseases");

        Bx10.setText("Dengue");

        Bx11.setText("Pregnancy");

        Bx9.setText("Surgery ");

        Bx12.setText("Hepatitis");
        Bx12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bx12ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        jLabel11.setText("Please tick thoes If you suffer from these conditions");

        SubmitBt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubmitBt.setText("Submit");
        SubmitBt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LeftPanelLayout = new javax.swing.GroupLayout(LeftPanel);
        LeftPanel.setLayout(LeftPanelLayout);
        LeftPanelLayout.setHorizontalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Bx10, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bx9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bx8)
                                    .addComponent(Bx4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Bx5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(LeftPanelLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SubmitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(LeftPanelLayout.createSequentialGroup()
                                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Bx12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bx11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bx6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bx7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bx3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Bx2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addComponent(Bx1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(47, 47, 47))
        );
        LeftPanelLayout.setVerticalGroup(
            LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bx9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Bx12))
                .addGap(26, 26, 26)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bx11)
                    .addComponent(Bx10))
                .addGap(26, 26, 26)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bx2)
                    .addComponent(Bx8))
                .addGap(26, 26, 26)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bx6)
                    .addComponent(Bx4))
                .addGap(26, 26, 26)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bx7)
                    .addComponent(Bx5))
                .addGap(26, 26, 26)
                .addGroup(LeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bx3)
                    .addComponent(Bx1))
                .addGap(18, 18, 18)
                .addComponent(SubmitBt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout containelPanelLayout = new javax.swing.GroupLayout(containelPanel);
        containelPanel.setLayout(containelPanelLayout);
        containelPanelLayout.setHorizontalGroup(
            containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        containelPanelLayout.setVerticalGroup(
            containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containelPanelLayout.createSequentialGroup()
                .addGroup(containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BgPanel.add(containelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 820, 480));

        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 510));

        Header.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("BLOOD BANK SYSTEM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 120));

        jLabel13.setIcon(new javax.swing.ImageIcon("/Users/kasun/Documents/JAVA Project/NewFolder/BloodBankSystem/src/Forms/Images/page2withnurse.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        InsertAndRetriewAdvacedDD IADR= new InsertAndRetriewAdvacedDD();
        try {
            IADR.RetriewDID(DID.getText());
            IADR.setLastDD(DID.getText());
            if(!IADR.getBtype(DID.getText()).equals(""))
            {
                Btype.setEnabled(false);
            }
            else{Btype.setEnabled(true);}
            if(DID.getText() == null ? IADR.getRdid() != null : !DID.getText().equals(IADR.getRdid()))
            {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Wrong  Dorner ID");
                HeightTxt.setEditable(false);
                WeightTxt.setEditable(false);
                LastDT.setEnabled(false);
                HeightTxt.setEditable(false);
                SubmitBt.setEnabled(false);
                setEnable(false);

            }
            else
            {
                IADR.RetriewDD(DID.getText());
                
                HeightTxt.setEditable(true);
                WeightTxt.setEditable(true);
                LastDT.setEnabled(true);
                HeightTxt.setEditable(true);
                SubmitBt.setEnabled(false);
                setEnable(true);
                if(IADR.CalculateAgeInMonths()==-1)
                {
                    JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can Donate Blood");
                }
                else if((IADR.CalculateAgeInMonths()>3))
                {
                     JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can Donate Blood");  
                }
                else{JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can't Donate Blood\n(Donated Blood Within 3 months)!!!!");
                HeightTxt.setEditable(false);
                WeightTxt.setEditable(false);
                LastDT.setEnabled(false);
                HeightTxt.setEditable(false);
                SubmitBt.setEnabled(false);
                setEnable(false);}
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
    }//GEN-LAST:event_SearchActionPerformed

public static boolean isAgeGreaterThan(String birthdateString, int minAge) {
        // Parse the birthdate string into a LocalDate object
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate birthdate = LocalDate.parse(birthdateString, formatter);

        LocalDate currentDate = LocalDate.now();
        Period age = Period.between(birthdate, currentDate);
        return age.getMonths() > minAge||age.getDays()== 0;}
    
    private void WeightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTxtActionPerformed

    private void DIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DIDActionPerformed

    private void DIDMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DIDMouseClicked
        // TODO add your handling code here:
        InsertAndRetriewAdvacedDD insert= new InsertAndRetriewAdvacedDD();
        try {
            BPID.setText(insert.GenerateBID());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_DIDMouseClicked

    private void HeightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightTxtActionPerformed

    private void LastDTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastDTMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_LastDTMouseClicked

    private void DIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DIDKeyReleased
       validateF(DID.getText(),"^(D0000)[1-9]|(D000)[1-9]{2}|(D000)[1-9]{1}[0]$",lblValidateDID); // TODO add your handling code here:
       check(); // TODO add your handling code here:
    }//GEN-LAST:event_DIDKeyReleased

    private void HeightTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HeightTxtKeyReleased
       validateF(HeightTxt.getText(),"^[1-9][5-9][0-9]$",lblValidateHeight); // TODO add your handling code here:
       check(); // TODO add your handling code here:
    }//GEN-LAST:event_HeightTxtKeyReleased

    private void WeightTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WeightTxtKeyReleased
         validateF(WeightTxt.getText(),"^[5-9][0-9]$",lblValidateWeight); // TODO add your handling code here:
         check(); // TODO add your handling code here:
    }//GEN-LAST:event_WeightTxtKeyReleased

    private void Bx12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bx12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bx12ActionPerformed

    private void Bx6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bx6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bx6ActionPerformed

    private void Bx5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bx5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Bx5ActionPerformed

    @SuppressWarnings("deprecation")
    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        AdminO fp = new AdminO();
        dispose();
        fp.show();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void SubmitBtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtActionPerformed
        InsertAndRetriewAdvacedDD IDorer = new InsertAndRetriewAdvacedDD();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat dfy = new SimpleDateFormat("yyyy");
        SimpleDateFormat dfm = new SimpleDateFormat("MM");
        SimpleDateFormat dfd = new SimpleDateFormat("dd");
        String Ldd= df.format(LastDT.getDate());
        if(IDorer.CalculateAgeInMonths(Integer.parseInt(dfy.format(LastDT.getDate())), Integer.parseInt(dfm.format(LastDT.getDate())), Integer.parseInt(dfd.format(LastDT.getDate())))>3||IDorer.CalculateAgeInMonths(Integer.parseInt(dfy.format(LastDT.getDate())), Integer.parseInt(dfm.format(LastDT.getDate())), Integer.parseInt(dfd.format(LastDT.getDate())))==0)
        {

            try {
                // TODO add your handling code here:

                String did = DID.getText();
                String btype;
                if(IDorer.getBtype(did).equals(""))
                {
                    btype=Btype.getSelectedItem().toString();

                }
                else
                {
                    btype= IDorer.getBtype(did);
                }

                double h = Double.valueOf(HeightTxt.getText());
                double w = Double.valueOf(WeightTxt.getText());
                boolean B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12;
                int sus;
                B1=Bx1.isSelected();
                B2=Bx2.isSelected();
                B3=Bx3.isSelected();
                B4=Bx4.isSelected();
                B5=Bx5.isSelected();
                B6=Bx6.isSelected();
                B7=Bx7.isSelected();
                B8=Bx8.isSelected();
                B9=Bx9.isSelected();
                B10=Bx10.isSelected();
                B11=Bx11.isSelected();
                B12=Bx12.isSelected();
                if(B1 || B2 || B3 || B4 || B5 || B6 || B7 || B8 || B9 || B10 || B11 || B12)
                {
                    sus=1;
                }
                else
                {
                    sus=0;
                }
                HgetBpacket gbp = new HgetBpacket();

                try {
                    IDorer.InsertD(did, btype, h, w, Ldd, sus);
                    gbp.UpdateStockTable();
                    JOptionPane.showMessageDialog(frame, "Data Entered Successfully");
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
                }
                Reset();
                setFalseChBox();

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IDorer.getDornerDetails()+"\nThis Dorner can't Donate Blood\n(Donated Blood Within 3 months)!!!!");
        }
    }//GEN-LAST:event_SubmitBtActionPerformed

    private void sqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrActionPerformed
        // TODO add your handling code here:
              // TODO add your handling code here:
        InsertAndRetriewAdvacedDD IADR= new InsertAndRetriewAdvacedDD();
        ScanQr scanqr = new ScanQr();
        String scnDid = scanqr.qrOut();
        DID.setText(scnDid);
        try {
            IADR.RetriewDID(DID.getText());
            IADR.setLastDD(DID.getText());
            if(!IADR.getBtype(DID.getText()).equals(""))
            {
                Btype.setEnabled(false);
            }
            else{Btype.setEnabled(true);}
            if(DID.getText() == null ? IADR.getRdid() != null : !DID.getText().equals(IADR.getRdid()))
            {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Wrong  Dorner ID");
                HeightTxt.setEditable(false);
                WeightTxt.setEditable(false);
                LastDT.setEnabled(false);
                HeightTxt.setEditable(false);
                SubmitBt.setEnabled(false);
                setEnable(false);

            }
            else
            {
                IADR.RetriewDD(DID.getText());
                
                HeightTxt.setEditable(true);
                WeightTxt.setEditable(true);
                LastDT.setEnabled(true);
                HeightTxt.setEditable(true);
                SubmitBt.setEnabled(true);
                setEnable(true);
                if(IADR.CalculateAgeInMonths()==-1)
                {
                    JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can Donate Blood");
                }
                else if((IADR.CalculateAgeInMonths()>3))
                {
                     JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can Donate Blood");  
                }
                else{JOptionPane.showMessageDialog(frame, "Avalable  Dorner ID \n\n"+IADR.getDornerDetails()+"\nThis Dorner can't Donate Blood\n(Donated Blood Within 3 months)!!!!");
                HeightTxt.setEditable(false);
                WeightTxt.setEditable(false);
                LastDT.setEnabled(false);
                HeightTxt.setEditable(false);
                SubmitBt.setEnabled(false);
                setEnable(false);}
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdvancedDD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
    }//GEN-LAST:event_sqrActionPerformed

    private void LastDTMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LastDTMousePressed
    // TODO add your handling code here:
        
        
    }//GEN-LAST:event_LastDTMousePressed

    private void LastDTInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_LastDTInputMethodTextChanged
      // TODO add your handling code here:
    }//GEN-LAST:event_LastDTInputMethodTextChanged

    private void LastDTComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_LastDTComponentAdded
            // TODO add your handling code here:
    }//GEN-LAST:event_LastDTComponentAdded

    private void LastDTPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_LastDTPropertyChange
           // TODO add your handling code here:
    }//GEN-LAST:event_LastDTPropertyChange

    private void LastDTVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_LastDTVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_LastDTVetoableChange

    public void Reset()
    {
        DID.setText("");
        Btype.setSelectedItem(0);
        HeightTxt.setText("");
        WeightTxt.setText("");
        LastDT.setDate(null);
        addError();
        SubmitBt.setEnabled(false);
        ResetBtn.setEnabled(false);    
    }
     public void check(){
//        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
//        String Ldd= df.format(LastDT.getDate());
//        boolean b= isAgeGreaterThan(Ldd, 3);
        if(lblValidateHeight.getForeground().equals(Color.green)&lblValidateWeight.getForeground().equals(Color.green)){
            SubmitBt.setEnabled(true);
        }else{
            SubmitBt.setEnabled(false);
        }
    }
    public void setFalseChBox()
    {
        Bx1.setSelected(false);
        Bx2.setSelected(false);
        Bx3.setSelected(false);
        Bx4.setSelected(false);
        Bx5.setSelected(false);
        Bx6.setSelected(false);
        Bx7.setSelected(false);
        Bx8.setSelected(false);
        Bx9.setSelected(false);
        Bx10.setSelected(false);
        Bx11.setSelected(false);
        Bx12.setSelected(false);
    }
     public void validateF(String text,String pattern,JLabel l1){
        ResetBtn.setEnabled(true);
        Pattern p=Pattern.compile(pattern);
        Matcher m=p.matcher(text);
        if(m.matches()){
            l1.setText("Valid input");
            l1.setForeground(Color.green);
        }else{
            l1.setText("Invalid input");
            l1.setForeground(Color.RED);
            
        }
    }
       public void addError(){
        lblValidateDID.setText(" ");
        lblValidateHeight.setText(" ");
        lblValidateWeight.setText(" ");
        lblValidateDID.setForeground(Color.red);
        lblValidateHeight.setForeground(Color.red);
        lblValidateWeight.setForeground(Color.red);
    }
    
    public void setEnable(boolean b)
    {
        Bx1.setEnabled(b);
        Bx2.setEnabled(b);
        Bx3.setEnabled(b);
        Bx4.setEnabled(b);
        Bx5.setEnabled(b);
        Bx6.setEnabled(b);
        Bx7.setEnabled(b);
        Bx8.setEnabled(b);
        Bx9.setEnabled(b);
        Bx10.setEnabled(b);
        Bx11.setEnabled(b);
        Bx12.setEnabled(b);
    }
    
    private boolean getSuspicious()
    {
        
        
        return (sus);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvancedDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvancedDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvancedDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvancedDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvancedDD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BPID;
    private javax.swing.JToggleButton BackBtn;
    private javax.swing.JPanel BgPanel;
    private javax.swing.JComboBox<String> Btype;
    private javax.swing.JCheckBox Bx1;
    private javax.swing.JCheckBox Bx10;
    private javax.swing.JCheckBox Bx11;
    private javax.swing.JCheckBox Bx12;
    private javax.swing.JCheckBox Bx2;
    private javax.swing.JCheckBox Bx3;
    private javax.swing.JCheckBox Bx4;
    private javax.swing.JCheckBox Bx5;
    private javax.swing.JCheckBox Bx6;
    private javax.swing.JCheckBox Bx7;
    private javax.swing.JCheckBox Bx8;
    private javax.swing.JCheckBox Bx9;
    private javax.swing.JTextField DID;
    private javax.swing.ButtonGroup GenderBtn;
    private javax.swing.JPanel Header;
    private javax.swing.JTextField HeightTxt;
    private com.toedter.calendar.JDateChooser LastDT;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JToggleButton ResetBtn;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JToggleButton Search;
    private javax.swing.JToggleButton SubmitBt;
    private javax.swing.JTextField WeightTxt;
    private javax.swing.JPanel containelPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblValidateDID;
    private javax.swing.JLabel lblValidateHeight;
    private javax.swing.JLabel lblValidateWeight;
    private javax.swing.JPanel rootPanel1;
    private javax.swing.JToggleButton sqr;
    // End of variables declaration//GEN-END:variables
}
