package Forms.DB;

import Blood_Bank.Generater;
import Blood_Bank.InsertAndRetriewAdvacedDD;
import Blood_Bank.InsertBasicDornerD;
import java.awt.Color;
import java.awt.Component;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kasun Dhananjaya
 */
public class BasicDD extends javax.swing.JFrame {

    /**
     * Creates new form FormForDoner
     */
    public BasicDD() {
        initComponents();
        addError();
        SubmitBtn.setEnabled(false);
        ResetBtn.setEnabled(false);
    }
    private String fname = "";
    private  String laname = "";
    private  String nic = "";
    private  String dob = null;
    private  int tel ;
    private  String no = "";
    private  String adl1 = "";
    private  String adl2 = "";
    private  String city = "";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderBtnGrp = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JToggleButton();
        ResetBtn = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        DID = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Fname = new javax.swing.JTextField();
        lblvalidateDOB = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblvalidateLname = new javax.swing.JLabel();
        Lname = new javax.swing.JTextField();
        FemaleBtn = new javax.swing.JRadioButton();
        MaleBtn = new javax.swing.JRadioButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NIC = new javax.swing.JTextField();
        lblvalidateNic = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DOB = new com.toedter.calendar.JDateChooser();
        lblvalidateFname1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblvalidateAdL3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Tel = new javax.swing.JTextField();
        lblvalidateTell = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        No = new javax.swing.JTextField();
        lblvalidateAdNo = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Adl = new javax.swing.JTextField();
        lblvalidateAdL1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Adl2 = new javax.swing.JTextField();
        lblvalidateAdL2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JToggleButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(153, 255, 255,35));

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(269, Short.MAX_VALUE)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 900, 120));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255,35));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 750));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(51, 204, 255,140));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 900, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dorner's Basic Details");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, -5, -1, 50));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 23, 37, -1));

        jPanel7.setBackground(new java.awt.Color(0, 0, 0,35));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ID");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        DID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DID.setText("ID");
        jPanel3.add(DID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("First Name");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        Fname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FnameMouseClicked(evt);
            }
        });
        Fname.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                FnameInputMethodTextChanged(evt);
            }
        });
        Fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameActionPerformed(evt);
            }
        });
        Fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameKeyReleased(evt);
            }
        });
        jPanel3.add(Fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 173, 30));

        lblvalidateDOB.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateDOB.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateDOB.setText("validate");
        jPanel3.add(lblvalidateDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 170, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Last Name");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lblvalidateLname.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateLname.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateLname.setText("validate");
        jPanel3.add(lblvalidateLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 170, -1));

        Lname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LnameMouseClicked(evt);
            }
        });
        Lname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameActionPerformed(evt);
            }
        });
        Lname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameKeyReleased(evt);
            }
        });
        jPanel3.add(Lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 173, 30));

        GenderBtnGrp.add(FemaleBtn);
        FemaleBtn.setText("Female");
        FemaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleBtnActionPerformed(evt);
            }
        });
        jPanel3.add(FemaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 98, -1));

        GenderBtnGrp.add(MaleBtn);
        MaleBtn.setText("Male");
        MaleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleBtnActionPerformed(evt);
            }
        });
        jPanel3.add(MaleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Gender");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("NIC");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        NIC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NICActionPerformed(evt);
            }
        });
        NIC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NICKeyReleased(evt);
            }
        });
        jPanel3.add(NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 242, 170, 30));

        lblvalidateNic.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateNic.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateNic.setText("validate");
        jPanel3.add(lblvalidateNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 160, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Date Of Birth");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        DOB.setDateFormatString("yyyy-MM-dd");
        DOB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOBMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DOBMouseEntered(evt);
            }
        });
        jPanel3.add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 170, -1));

        lblvalidateFname1.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateFname1.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateFname1.setText("validate");
        jPanel3.add(lblvalidateFname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 170, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblvalidateAdL3.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateAdL3.setFont(new java.awt.Font("Yu Gothic UI Light", 3, 14)); // NOI18N
        lblvalidateAdL3.setText("validate");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Telephone");

        Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelActionPerformed(evt);
            }
        });
        Tel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TelKeyReleased(evt);
            }
        });

        lblvalidateTell.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateTell.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateTell.setText("validate");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("No");

        No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoActionPerformed(evt);
            }
        });
        No.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NoKeyReleased(evt);
            }
        });

        lblvalidateAdNo.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateAdNo.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateAdNo.setText("validate");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Line 1");

        Adl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdlActionPerformed(evt);
            }
        });
        Adl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AdlKeyReleased(evt);
            }
        });

        lblvalidateAdL1.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateAdL1.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateAdL1.setText("validate");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Line 2");

        Adl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Adl2ActionPerformed(evt);
            }
        });
        Adl2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Adl2KeyReleased(evt);
            }
        });

        lblvalidateAdL2.setBackground(new java.awt.Color(204, 204, 204));
        lblvalidateAdL2.setFont(new java.awt.Font("Yu Gothic Light", 3, 14)); // NOI18N
        lblvalidateAdL2.setText("validate");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("City/District");

        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        City.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                CityKeyReleased(evt);
            }
        });

        SubmitBtn.setBackground(new java.awt.Color(102, 255, 51));
        SubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SubmitBtn.setText("Submit");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Address");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(37, 37, 37)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblvalidateAdNo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblvalidateTell, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblvalidateAdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblvalidateAdL3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblvalidateAdL2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(No, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                .addComponent(Adl)
                                .addComponent(Adl2)
                                .addComponent(City)
                                .addComponent(Tel)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Tel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(lblvalidateTell)
                        .addGap(25, 25, 25)
                        .addComponent(No, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvalidateAdNo)
                .addGap(1, 1, 1)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Adl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblvalidateAdL1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(Adl2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addComponent(lblvalidateAdL2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(City, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblvalidateAdL3)
                .addGap(18, 18, 18)
                .addComponent(SubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 820, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 520));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("BLOOD BANK SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(150, 150, 150))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 160));

        jLabel1.setBackground(new java.awt.Color(153, 255, 255,45));
        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/kasun/Documents/JAVA Project/NewFolder/BloodBankSystem/src/Forms/Images/page2withnurse.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void Rest()
    {
        DID.setText("ID");
        Fname.setText("");
        Lname.setText("");
        Tel.setText("");
        DOB.setDate(null);
        No.setText("");
        Adl.setText("");
        Adl2.setText("");
        City.setText("");
        NIC.setText("");
        addError();
        SubmitBtn.setEnabled(false);
        ResetBtn.setEnabled(false);
    }
     public void check(){
        if(lblvalidateFname1.getForeground().equals(Color.green)&lblvalidateLname.getForeground().equals(Color.green)&lblvalidateNic.getForeground().equals(Color.green)&lblvalidateTell.getForeground().equals(Color.green)&lblvalidateAdNo.getForeground().equals(Color.green)&lblvalidateAdL1.getForeground().equals(Color.green)&lblvalidateAdL2.getForeground().equals(Color.green)&lblvalidateAdL3.getForeground().equals(Color.green)){
            SubmitBtn.setEnabled(true);
        }else{
            SubmitBtn.setEnabled(false);
        }
    }
    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
     
        Rest();
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        FPage fp = new FPage();
        fp.show();
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed
        public void validateF(String text,String pattern,JLabel l1){
        ResetBtn.setEnabled(true);
        Pattern p=Pattern.compile(pattern);
        Matcher m=p.matcher(text);
        if(m.matches()){
            l1.setText("Valid input");
            l1.setForeground(Color.green);
        }else{
            l1.setText("Invalid input");
            l1.setForeground(Color.RED);
            
        }
    }
    public void addError(){
        lblvalidateDOB.setText(" ");
        lblvalidateLname.setText(" ");
        lblvalidateFname1.setText(" ");
        lblvalidateNic.setText(" ");
        lblvalidateTell.setText(" ");
        lblvalidateAdNo.setText(" ");
        lblvalidateAdL1.setText(" ");
        lblvalidateAdL2.setText(" ");
        lblvalidateAdL3.setText(" ");
        lblvalidateDOB.setForeground(Color.red);
        lblvalidateLname.setForeground(Color.red);
        lblvalidateNic.setForeground(Color.red);
        lblvalidateTell.setForeground(Color.red);
        lblvalidateAdNo.setForeground(Color.red);
        lblvalidateAdL1.setForeground(Color.red);
        lblvalidateAdL2.setForeground(Color.red);
        lblvalidateAdL3.setForeground(Color.red);
        
    }
    public static boolean isAgeGreaterThan18(String birthDateString) {
        LocalDate birthDate = LocalDate.parse(birthDateString, DateTimeFormatter.ofPattern("yyyy-MM-dd"));
        LocalDate today = LocalDate.now();
        Period period = Period.between(birthDate, today);
        int age = period.getYears();
        return age > 18;
    }
    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
// TODO add your handling code here:
        MaleBtn.setActionCommand("Male");
        FemaleBtn.setActionCommand("Female");
        fname=Fname.getText();
        laname=Lname.getText();
        nic=NIC.getText();
        tel=parseInt(Tel.getText());
        no=No.getText();
        SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        dob= df.format(DOB.getDate());
        adl1=Adl.getText();
        adl2=Adl2.getText();
        city=City.getText();
        InsertBasicDornerD IBDD= new InsertBasicDornerD();
        String gender=GenderBtnGrp.getSelection().getActionCommand();
        String Lbldid= DID.getText();
        Generater gn = new Generater();
        if(isAgeGreaterThan18(dob))
        {
        //qr.show();
        try {
           
            IBDD.InsertD(fname, laname, nic, dob, tel, no, adl1, adl2, city,gender);
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Data Entered Successfully \n ");
            gn.generateQr(Lbldid);
            Rest();
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        else{Component frame = null;
JOptionPane.showMessageDialog(frame, "Your Age under 18 \n You can't Donate Blood");
        }
     
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void FemaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemaleBtnActionPerformed

    private void MaleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaleBtnActionPerformed

    private void LnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameKeyReleased
        InsertBasicDornerD IBDD= new InsertBasicDornerD();
        try {
            DID.setText(IBDD.GenerateDID());
        } catch (SQLException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        } // TODO add your handling code here:
        validateF(Lname.getText(),"^[A-z ]{3,20}$",lblvalidateLname);
        check();// TODO add your handling code here:
    }//GEN-LAST:event_LnameKeyReleased

    private void LnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameActionPerformed

    private void LnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LnameMouseClicked
        // TODO add your handling code here:
        InsertBasicDornerD IBDD= new InsertBasicDornerD();
        try {
            DID.setText(IBDD.GenerateDID());
        } catch (SQLException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LnameMouseClicked
    private void DOBReleased(java.awt.event.KeyEvent evt) {  
        // TODO add your handling code here:
        
    } 
    
    private void CityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CityKeyReleased
        validateF(City.getText(),"^[A-z ]{3,20}$",lblvalidateAdL3); // TODO add your handling code here:
        check(); // TODO add your handling code here:
    }//GEN-LAST:event_CityKeyReleased

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void Adl2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Adl2KeyReleased
        validateF(Adl2.getText(),"^[A-z ]{3,20}$",lblvalidateAdL2); // TODO add your handling code here:
        check(); // TODO add your handling code here:
    }//GEN-LAST:event_Adl2KeyReleased

    private void Adl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Adl2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Adl2ActionPerformed

    private void AdlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AdlKeyReleased
        validateF(Adl.getText(),"^[A-z ]{3,20}$",lblvalidateAdL1);// TODO add your handling code here:
        check(); // TODO add your handling code here:
    }//GEN-LAST:event_AdlKeyReleased

    private void AdlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdlActionPerformed

    private void NoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoKeyReleased
        validateF(No.getText(),"^[1-9][1-9]{0,4}|[1-9][0-9]{2,3}[A-Z]|[1-9][0-9]{1,3}[ /A-Z]{1,6}[1-9]|[1-9][0-9]{1,3}[ /A-Z]{1,6}$",lblvalidateAdNo); // TODO add your handling code here:
        check();        // TODO add your handling code here:
    }//GEN-LAST:event_NoKeyReleased

    private void NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoActionPerformed

    private void TelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelKeyReleased
        validateF(Tel.getText(),"^[0][0-9]{9}$",lblvalidateTell);// TODO add your handling code here:
        check();        // TODO add your handling code here:
    }//GEN-LAST:event_TelKeyReleased

    private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelActionPerformed

    private void FnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameKeyReleased
        validateF(Fname.getText(),"^[A-z ]{3,20}$",lblvalidateFname1); // TODO add your handling code here:
        check(); // TODO add your handling code here:
    }//GEN-LAST:event_FnameKeyReleased

    private void FnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameActionPerformed
        // TODO add your handling code here:
        InsertBasicDornerD IBDD= new InsertBasicDornerD();
        try {
            DID.setText(IBDD.GenerateDID());
        } catch (SQLException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FnameActionPerformed

    private void FnameInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_FnameInputMethodTextChanged

    }//GEN-LAST:event_FnameInputMethodTextChanged

    private void FnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FnameMouseClicked
        // TODO add your handling code here:
        InsertBasicDornerD IBDD= new InsertBasicDornerD();
        try {
            DID.setText(IBDD.GenerateDID());
        } catch (SQLException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BasicDD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_FnameMouseClicked

    private void NICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NICKeyReleased
        validateF(NIC.getText(),"^[1-9][0-9]{11}|[1-9][0-9]{8}[v]$",lblvalidateNic);// TODO add your handling code here:
        check();// TODO add your handling code here:
    }//GEN-LAST:event_NICKeyReleased

    private void NICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NICActionPerformed

    private void DOBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseClicked
    // TODO add your handling code here:
    }//GEN-LAST:event_DOBMouseClicked

    private void DOBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBMouseEntered
                   
    /** 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicDD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BasicDD().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Adl;
    private javax.swing.JTextField Adl2;
    private javax.swing.JToggleButton BackBtn;
    private javax.swing.JTextField City;
    private javax.swing.JLabel DID;
    private com.toedter.calendar.JDateChooser DOB;
    private javax.swing.JRadioButton FemaleBtn;
    private javax.swing.JTextField Fname;
    private javax.swing.ButtonGroup GenderBtnGrp;
    private javax.swing.JTextField Lname;
    private javax.swing.JRadioButton MaleBtn;
    private javax.swing.JTextField NIC;
    private javax.swing.JTextField No;
    private javax.swing.JToggleButton ResetBtn;
    private javax.swing.JToggleButton SubmitBtn;
    private javax.swing.JTextField Tel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblvalidateAdL1;
    private javax.swing.JLabel lblvalidateAdL2;
    private javax.swing.JLabel lblvalidateAdL3;
    private javax.swing.JLabel lblvalidateAdNo;
    private javax.swing.JLabel lblvalidateDOB;
    private javax.swing.JLabel lblvalidateFname1;
    private javax.swing.JLabel lblvalidateLname;
    private javax.swing.JLabel lblvalidateNic;
    private javax.swing.JLabel lblvalidateTell;
    // End of variables declaration//GEN-END:variables

    private String dateFormat(Date date) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
