package Forms.DB;

import Blood_Bank.DornerAndPatientDetailsR;
import java.awt.Color;
import java.awt.Component;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kasun Dhananjaya
 */
public class DornerDetailsRetrive extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public DornerDetailsRetrive() {
        initComponents();
        addError();
        FnameTxt.setEnabled(false);
        LnameTxt.setEnabled(false);
        DIDtxt.setEnabled(false);
        WnoTxt.setEnabled(false);
        BnoTxt.setEnabled(false);
        DateTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        SearchBtn = new javax.swing.JToggleButton();
        BackBtn = new javax.swing.JToggleButton();
        DateTxt = new javax.swing.JTextField();
        lblValidateDate = new javax.swing.JLabel();
        lblValidateBedNo = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BnoTxt = new javax.swing.JTextField();
        WnoTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblValidateWNo = new javax.swing.JLabel();
        lblValidateDID = new javax.swing.JLabel();
        DIDtxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        LnameTxt = new javax.swing.JTextField();
        lblValidateLname = new javax.swing.JLabel();
        lblValidateFname = new javax.swing.JLabel();
        FnameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        DornerBtn = new javax.swing.JRadioButton();
        PatientBtn = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jPanel4.setBackground(new java.awt.Color(153, 255, 255,70));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BLOOD BANK SYSTEM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 120));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DID", "First Name", "Last Name", "ID", "No", "Adl1", "Adl2", "City", "Btype", "Date", "Wno", "Bed_no"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        SearchBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });

        BackBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        DateTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DateTxtMouseClicked(evt);
            }
        });
        DateTxt.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                DateTxtInputMethodTextChanged(evt);
            }
        });
        DateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTxtActionPerformed(evt);
            }
        });
        DateTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DateTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DateTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DateTxtKeyTyped(evt);
            }
        });

        lblValidateDate.setText("jLabel27");

        lblValidateBedNo.setText("jLabel26");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Issued Date");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Bed Number");

        BnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BnoTxtActionPerformed(evt);
            }
        });
        BnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BnoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BnoTxtKeyReleased(evt);
            }
        });

        WnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WnoTxtActionPerformed(evt);
            }
        });
        WnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WnoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WnoTxtKeyReleased(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Word Number");

        lblValidateWNo.setText("jLabel25");

        lblValidateDID.setText("jLabel24");
        lblValidateDID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblValidateDIDKeyReleased(evt);
            }
        });

        DIDtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DIDtxtActionPerformed(evt);
            }
        });
        DIDtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                DIDtxtKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("DID");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Last Name");

        LnameTxt.setPreferredSize(new java.awt.Dimension(7, 20));
        LnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LnameTxtActionPerformed(evt);
            }
        });
        LnameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LnameTxtKeyReleased(evt);
            }
        });

        lblValidateLname.setText("jLabel23");

        lblValidateFname.setText("jLabel22");

        FnameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FnameTxtActionPerformed(evt);
            }
        });
        FnameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                FnameTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FnameTxtKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("First Name");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Select Option");

        buttonGroup1.add(DornerBtn);
        DornerBtn.setText("Patient");
        DornerBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DornerBtnItemStateChanged(evt);
            }
        });

        buttonGroup1.add(PatientBtn);
        PatientBtn.setText("Dorner");
        PatientBtn.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                PatientBtnItemStateChanged(evt);
            }
        });

        jLabel1.setText("Search By Doner Details");

        jLabel12.setText("Search by Patient Details");

        jLabel13.setText(" (MM) OR (DD) ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109)
                        .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(126, 126, 126)
                                        .addComponent(lblValidateDID))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(55, 55, 55)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblValidateLname)
                                        .addComponent(LnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValidateFname)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel10))
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(WnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValidateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblValidateBedNo)
                                        .addComponent(lblValidateWNo))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DornerBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(PatientBtn))
                                    .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(81, 81, 81))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel1)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(54, 54, 54)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(DornerBtn)
                    .addComponent(PatientBtn))
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(lblValidateFname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(LnameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidateLname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DIDtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidateDID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(WnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValidateWNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BnoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblValidateBedNo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblValidateDate)
                    .addComponent(jLabel13))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 996, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 946, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jLabel2))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        SearchBtn.setEnabled(false);
    }//GEN-LAST:event_formWindowActivated

    private void FnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FnameTxtActionPerformed

    private void DIDtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DIDtxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DIDtxtActionPerformed

    private void LnameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LnameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LnameTxtActionPerformed

    private void BnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BnoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BnoTxtActionPerformed

    private void WnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WnoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WnoTxtActionPerformed

    private void DateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTxtActionPerformed

    private void DornerBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DornerBtnItemStateChanged
        // TODO add your handling code here:
        if(DornerBtn.isSelected())
        {
            addError();
            reset();
            FnameTxt.setEnabled(false);
            LnameTxt.setEnabled(false);
            DIDtxt.setEnabled(false);
            WnoTxt.setEnabled(true);
            BnoTxt.setEnabled(true);
            DateTxt.setEnabled(true);
        }
    }//GEN-LAST:event_DornerBtnItemStateChanged

    private void PatientBtnItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_PatientBtnItemStateChanged
        // TODO add your handling code here:
        if(PatientBtn.isSelected())
        {
            addError();
            reset();
            WnoTxt.setEnabled(false);
            BnoTxt.setEnabled(false);
            DateTxt.setEnabled(false);
            FnameTxt.setEnabled(true);
            LnameTxt.setEnabled(true);
            DIDtxt.setEnabled(true);
        }
    }//GEN-LAST:event_PatientBtnItemStateChanged

    private void DateTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTxtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DateTxtKeyTyped

    private void DateTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTxtKeyPressed
        validateF(DateTxt.getText(), "^[0-9]$",lblValidateDate); // TODO add your handling code here:
        check();
    }//GEN-LAST:event_DateTxtKeyPressed

    private void BnoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BnoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BnoTxtKeyPressed

    private void BnoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BnoTxtKeyReleased
       validateF(BnoTxt.getText(),"^[0-9]{1,2}$",lblValidateBedNo); // TODO add your handling code here:
       check(); // TODO add your handling code here:

    }//GEN-LAST:event_BnoTxtKeyReleased

    private void WnoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WnoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_WnoTxtKeyPressed

    private void WnoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WnoTxtKeyReleased
       validateF(WnoTxt.getText(),"^[0-9]{1,2}$",lblValidateWNo); // TODO add your handling code here:
       check(); // TODO add your handling code here:
    }//GEN-LAST:event_WnoTxtKeyReleased

    private void DateTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DateTxtKeyReleased
        // TODO add your handling code here:
         
    }//GEN-LAST:event_DateTxtKeyReleased

    private void DateTxtInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_DateTxtInputMethodTextChanged
        // TODO add your handling code here:
           
    }//GEN-LAST:event_DateTxtInputMethodTextChanged

    private void DateTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DateTxtMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_DateTxtMouseClicked

    public void clearTable()
    {
    DefaultTableModel dm = (DefaultTableModel) Table.getModel();
    dm.getDataVector().removeAllElements();
    revalidate();
    }
    public void table()
    {
        DornerAndPatientDetailsR dpdr= new DornerAndPatientDetailsR();
        try {
            DefaultTableModel model=(DefaultTableModel) Table.getModel();
            dpdr.setDPdetails(WnoTxt.getText(), BnoTxt.getText(), DIDtxt.getText(), DIDtxt.getText(), FnameTxt.getText(), LnameTxt.getText());
            if(dpdr.getLength()==0)
            {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Not Donated Dorner's Blood Packet");
            }
               
            while(i<dpdr.getLength())
            {
                model.addRow(new Object[]{dpdr.getDornerAndPatientDetails(i, 0),dpdr.getDornerAndPatientDetails(i, 1),dpdr.getDornerAndPatientDetails(i, 2),dpdr.getDornerAndPatientDetails(i, 3),dpdr.getDornerAndPatientDetails(i, 4),dpdr.getDornerAndPatientDetails(i, 5),dpdr.getDornerAndPatientDetails(i, 6),dpdr.getDornerAndPatientDetails(i, 7),dpdr.getDornerAndPatientDetails(i, 8),dpdr.getDornerAndPatientDetails(i, 9),dpdr.getDornerAndPatientDetails(i, 10),dpdr.getDornerAndPatientDetails(i, 11)});
                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DornerDetailsRetrive.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DornerDetailsRetrive.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void reset()
    {
        WnoTxt.setText("");
        FnameTxt.setText("");
        LnameTxt.setText("");
        DIDtxt.setText("");
        WnoTxt.setText("");
        BnoTxt.setText("");
        DIDtxt.setText("");
        DornerBtn.setSelected(false);
        PatientBtn.setSelected(false);
        FnameTxt.setEnabled(false);
        LnameTxt.setEnabled(false);
        DIDtxt.setEnabled(false);
        WnoTxt.setEnabled(false);
        BnoTxt.setEnabled(false);
        DateTxt.setEnabled(false);
    }
    public void validateF(String text,String pattern,JLabel l1){
        Pattern p=Pattern.compile(pattern);
        Matcher m=p.matcher(text);
        if(m.matches()){
                            l1.setText("Valid input");
                            l1.setForeground(Color.green);
        }else{
                            l1.setText("Invalid input");
                            l1.setForeground(Color.RED);
        }
    }
     public void check(){
        if(DornerBtn.isSelected()&lblValidateWNo.getForeground().equals(Color.green)&lblValidateBedNo.getForeground().equals(Color.green)&lblValidateDate.getForeground().equals(Color.green)){
                SearchBtn.setEnabled(true);
        }else if (PatientBtn.isSelected()&lblValidateFname.getForeground().equals(Color.green)|lblValidateLname.getForeground().equals(Color.green)|lblValidateDID.getForeground().equals(Color.green)) {
                SearchBtn.setEnabled(true);
         }
    }
     public void addError(){
        lblValidateLname.setText(" ");
        lblValidateFname.setText(" ");
        lblValidateDID.setText(" ");
        lblValidateWNo.setText(" ");
        lblValidateBedNo.setText(" ");
        lblValidateDate.setText(" ");
        
       
        lblValidateFname.setForeground(Color.red);
        lblValidateBedNo.setForeground(Color.red);
        lblValidateLname.setForeground(Color.red);
        lblValidateWNo.setForeground(Color.red);
        lblValidateDate.setForeground(Color.red);
        lblValidateDID.setForeground(Color.red);
     }
    int i=0;
    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:
    clearTable();
    table();
    reset();
    
        
    }//GEN-LAST:event_SearchBtnActionPerformed
    private void FnameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameTxtKeyPressed
        // TODO add your handling code here:
        if(FnameTxt.getText().equals("")&&LnameTxt.getText().equals("")&&DIDtxt.getText().equals("")&&DornerBtn.isSelected())
        {
            SearchBtn.setEnabled(false);
        }
        else{SearchBtn.setEnabled(true);}
    }//GEN-LAST:event_FnameTxtKeyPressed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        AdminO ado = new AdminO();
        ado.show();
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void FnameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FnameTxtKeyReleased
       validateF(FnameTxt.getText(),"^[A-z ]{3,20}$",lblValidateFname); // TODO add your handling code here:
       check();// TODO add your handling code here:
    }//GEN-LAST:event_FnameTxtKeyReleased

    private void LnameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LnameTxtKeyReleased
       validateF(LnameTxt.getText(),"^[A-z ]{3,20}$",lblValidateLname);
       check(); // TODO add your handling code here:
    }//GEN-LAST:event_LnameTxtKeyReleased

    private void lblValidateDIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblValidateDIDKeyReleased
 // TODO add your handling code here:
    }//GEN-LAST:event_lblValidateDIDKeyReleased

    private void DIDtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DIDtxtKeyReleased
        validateF(DIDtxt.getText(),"^(D0000)[1-9]|(D000)[1-9]{2}$",lblValidateDID); // TODO add your handling code here:
        check();        // TODO add your handling code here:
    }//GEN-LAST:event_DIDtxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DornerDetailsRetrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DornerDetailsRetrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DornerDetailsRetrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DornerDetailsRetrive.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DornerDetailsRetrive().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BackBtn;
    private javax.swing.JTextField BnoTxt;
    private javax.swing.JTextField DIDtxt;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JRadioButton DornerBtn;
    private javax.swing.JTextField FnameTxt;
    private javax.swing.JTextField LnameTxt;
    private javax.swing.JRadioButton PatientBtn;
    private javax.swing.JToggleButton SearchBtn;
    private javax.swing.JTable Table;
    private javax.swing.JTextField WnoTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblValidateBedNo;
    private javax.swing.JLabel lblValidateDID;
    private javax.swing.JLabel lblValidateDate;
    private javax.swing.JLabel lblValidateFname;
    private javax.swing.JLabel lblValidateLname;
    private javax.swing.JLabel lblValidateWNo;
    // End of variables declaration//GEN-END:variables
}
