package Forms.DB;

import Blood_Bank.LoginToSicurityDB;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kasun Dhananjaya
 */
public class FPage extends javax.swing.JFrame {

    /**
     * Creates new form FirstPage
     */
    public FPage() {
        initComponents();
    }
    private String Privilage;
    public void setPrivilage(String privilage)
    {
        this.Privilage= privilage;
    }
    public String getPrivilage()
    {
        return(this.Privilage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffBtn = new javax.swing.JToggleButton();
        NewDornerBtn = new javax.swing.JToggleButton();
        ICTcBtn = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        StaffBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        StaffBtn.setText("Staff");
        StaffBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffBtnActionPerformed(evt);
            }
        });
        getContentPane().add(StaffBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 160, 80));

        NewDornerBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        NewDornerBtn.setText("New Doner");
        NewDornerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewDornerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(NewDornerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 150, 80));

        ICTcBtn.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        ICTcBtn.setText("ICT Center");
        ICTcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ICTcBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ICTcBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 150, 80));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("BLOOD BANK SYSTEM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 160));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/kasun/Documents/JAVA Project/NewFolder/BloodBankSystem/src/Forms/Images/page2withnurse.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("deprecation")
    private void NewDornerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewDornerBtnActionPerformed
        // TODO add your handling code here:
        BasicDD bDD = new BasicDD();
        bDD.show();
        dispose();  
    }//GEN-LAST:event_NewDornerBtnActionPerformed

    @SuppressWarnings("deprecation")
    private void StaffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffBtnActionPerformed
        // TODO add your handling code here:
        BasicLF basiclf= new BasicLF();
        BasicLF1WithinNewPword basiclfwp= new BasicLF1WithinNewPword();
        setPrivilage("staff");
        basiclf.setPrivilage("staff");
        basiclfwp.setPrivilage("staff");
        LoginToSicurityDB lts = new LoginToSicurityDB();
        try {
            lts.Retriew(getPrivilage());
            if(lts.getQureyout().equals("")){
             basiclfwp.show();
            dispose();}
            else
        {
            basiclf.show();
                dispose();
        }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(FPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FPage.class.getName()).log(Level.SEVERE, null, ex);
        }    
        
        
    }//GEN-LAST:event_StaffBtnActionPerformed

    @SuppressWarnings("deprecation")
    private void ICTcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ICTcBtnActionPerformed
        // TODO add your handling code here:
        BasicLF1WithinNewPword basiclfwp= new BasicLF1WithinNewPword();
        BasicLF basiclf= new BasicLF();
        basiclfwp.setPrivilage("ICT");
        setPrivilage("ICT");
        basiclf.setPrivilage("ICT");
        LoginToSicurityDB lts = new LoginToSicurityDB();
 
        try {
            lts.Retriew(getPrivilage());
            if(lts.getQureyout().equals("")){
             basiclfwp.show();
            dispose();}
            else
        {
            basiclf.show();
                dispose();
        }  
        } catch (SQLException ex) {
            Logger.getLogger(FPage.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FPage.class.getName()).log(Level.SEVERE, null, ex);
        }  
    }//GEN-LAST:event_ICTcBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ICTcBtn;
    private javax.swing.JToggleButton NewDornerBtn;
    private javax.swing.JToggleButton StaffBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
