package Forms.DB;

import Blood_Bank.HgetBpacket;
import java.awt.Color;
import java.awt.Component;
import static java.lang.Integer.parseInt;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Kasun Dhananjaya
 */
public class HGetBP extends javax.swing.JFrame {
    private String SelectedBType;
    /**
     * Creates new form AdminOption
     */
    public HGetBP() {
        initComponents();
        addError();
        SubmitBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        buttonGroup1 = new javax.swing.ButtonGroup();
        rootPanel1 = new javax.swing.JPanel();
        BackBtn = new javax.swing.JToggleButton();
        BgPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        containelPanel = new javax.swing.JPanel();
        RightPanel = new javax.swing.JPanel();
        RcatogoryBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        CountSpr = new javax.swing.JSpinner();
        BloodTypeSelection = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        YesBtn = new javax.swing.JRadioButton();
        NoBtn = new javax.swing.JRadioButton();
        ABloodTypeSelection = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        LeftPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        WnoTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BedNoTxt = new javax.swing.JTextField();
        lblValidateWeight = new javax.swing.JLabel();
        lblValidateAge = new javax.swing.JLabel();
        AgeTxt = new javax.swing.JTextField();
        lblValidateBedNo = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblValidateWardNo = new javax.swing.JLabel();
        WeightTxt = new javax.swing.JTextField();
        SubmitBtn = new javax.swing.JToggleButton();
        Header = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rootPanel1.setBackground(new java.awt.Color(153, 255, 255,35));

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rootPanel1Layout = new javax.swing.GroupLayout(rootPanel1);
        rootPanel1.setLayout(rootPanel1Layout);
        rootPanel1Layout.setHorizontalGroup(
            rootPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(668, Short.MAX_VALUE))
        );
        rootPanel1Layout.setVerticalGroup(
            rootPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rootPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(BackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(rootPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 900, 120));

        BgPanel.setBackground(new java.awt.Color(153, 255, 255,35));
        BgPanel.setPreferredSize(new java.awt.Dimension(900, 750));
        BgPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Blood Requesting Form");
        BgPanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, 50));

        containelPanel.setBackground(new java.awt.Color(0, 0, 0,35));

        RightPanel.setBackground(new java.awt.Color(255, 255, 255));

        RcatogoryBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Routine", "Urgent", "Emergency" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Blood Type");

        CountSpr.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));
        CountSpr.setPreferredSize(new java.awt.Dimension(0, 22));

        BloodTypeSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-" }));
        BloodTypeSelection.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BloodTypeSelectionItemStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Request caregory");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Not be able to use other blood types");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Count");

        buttonGroup1.add(YesBtn);
        YesBtn.setText("Yes");
        YesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                YesBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                YesBtnMouseEntered(evt);
            }
        });
        YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(NoBtn);
        NoBtn.setSelected(true);
        NoBtn.setText("No");
        NoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoBtnMouseClicked(evt);
            }
        });
        NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoBtnActionPerformed(evt);
            }
        });
        NoBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NoBtnKeyPressed(evt);
            }
        });

        ABloodTypeSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABloodTypeSelectionActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Alternative Blood Types");

        javax.swing.GroupLayout RightPanelLayout = new javax.swing.GroupLayout(RightPanel);
        RightPanel.setLayout(RightPanelLayout);
        RightPanelLayout.setHorizontalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16)
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14))
                        .addGap(63, 63, 63)
                        .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RcatogoryBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BloodTypeSelection, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CountSpr, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addComponent(YesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(NoBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RightPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ABloodTypeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        RightPanelLayout.setVerticalGroup(
            RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RightPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(RcatogoryBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(BloodTypeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CountSpr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(42, 42, 42)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesBtn)
                    .addComponent(NoBtn))
                .addGap(39, 39, 39)
                .addGroup(RightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ABloodTypeSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        LeftPanel.setBackground(new java.awt.Color(255, 255, 255));
        LeftPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Weight");
        LeftPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 60, -1));

        WnoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WnoTxtActionPerformed(evt);
            }
        });
        WnoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WnoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WnoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WnoTxtKeyTyped(evt);
            }
        });
        LeftPanel.add(WnoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 53, 102, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Ward no");
        LeftPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 53, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setText("Patient details :");
        LeftPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 145, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Bed no");
        LeftPanel.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 131, -1, -1));

        BedNoTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BedNoTxtActionPerformed(evt);
            }
        });
        BedNoTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BedNoTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BedNoTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                BedNoTxtKeyTyped(evt);
            }
        });
        LeftPanel.add(BedNoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 132, 100, 20));

        lblValidateWeight.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblValidateWeight.setText("Validate");
        LeftPanel.add(lblValidateWeight, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 100, -1));

        lblValidateAge.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblValidateAge.setText("Validate");
        LeftPanel.add(lblValidateAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 130, -1));

        AgeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeTxtActionPerformed(evt);
            }
        });
        AgeTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                AgeTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                AgeTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                AgeTxtKeyTyped(evt);
            }
        });
        LeftPanel.add(AgeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 213, 100, -1));

        lblValidateBedNo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblValidateBedNo.setText("Validate");
        LeftPanel.add(lblValidateBedNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 110, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setText("Age");
        LeftPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 213, -1, -1));

        lblValidateWardNo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblValidateWardNo.setText("Validate");
        LeftPanel.add(lblValidateWardNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 82, 120, -1));

        WeightTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeightTxtActionPerformed(evt);
            }
        });
        WeightTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                WeightTxtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                WeightTxtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                WeightTxtKeyTyped(evt);
            }
        });
        LeftPanel.add(WeightTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 100, -1));

        SubmitBtn.setText("Make Order");
        SubmitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitBtnMouseEntered(evt);
            }
        });
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        LeftPanel.add(SubmitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 160, 57));

        javax.swing.GroupLayout containelPanelLayout = new javax.swing.GroupLayout(containelPanel);
        containelPanel.setLayout(containelPanelLayout);
        containelPanelLayout.setHorizontalGroup(
            containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        containelPanelLayout.setVerticalGroup(
            containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containelPanelLayout.createSequentialGroup()
                .addGroup(containelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE))
                .addContainerGap())
        );

        BgPanel.add(containelPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 820, 480));

        getContentPane().add(BgPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 510));

        Header.setBackground(new java.awt.Color(0, 0, 0,140
        ));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Ubuntu Mono", 1, 72)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("BLOOD BANK SYSTEM");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderLayout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 120));

        jLabel24.setIcon(new javax.swing.ImageIcon("/Users/kasun/Documents/JAVA Project/NewFolder/BloodBankSystem/src/Forms/Images/page2withnurse.jpg")); // NOI18N
        jLabel24.setText("jLabel13");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BedNoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BedNoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedNoTxtActionPerformed

    private void AgeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtActionPerformed

    private void WeightTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeightTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeightTxtActionPerformed

    private void WnoTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WnoTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WnoTxtActionPerformed

    private void BloodTypeSelectionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BloodTypeSelectionItemStateChanged
        // TODO add your handling code here:
       
        SelectedBType = BloodTypeSelection.getSelectedItem().toString();
        String OldSelectedBtype= SelectedBType;
        HgetBpacket bp = new HgetBpacket();
        try {
            ABloodTypeSelection.removeAllItems();
            ABloodTypeSelection.addItem(SelectedBType);
            bp.getPreferableType(SelectedBType);
            for(int i=0;i<8;i++){
            if(bp.getBloodType(i) == null ? OldSelectedBtype == null : bp.getBloodType(i).equals(OldSelectedBtype))
            {
                continue;
            }
            else if(bp.getBloodType(i)!=null)
            {
                ABloodTypeSelection.addItem(bp.getBloodType(i));
            }
            else
            {
                break;
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BloodTypeSelectionItemStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        //rest();
        SubmitBtn.setEnabled(false);
        YesBtn.setActionCommand("Yes");
        NoBtn.setActionCommand("No");
        SelectedBType = BloodTypeSelection.getSelectedItem().toString();
        HgetBpacket bp = new HgetBpacket();
        try {
            ABloodTypeSelection.removeAllItems();
            bp.getPreferableType(SelectedBType);
            for(int i=0;i<8;i++){
            if(bp.getBloodType(i)!=null)
            {
                ABloodTypeSelection.addItem(bp.getBloodType(i));
            }
            else
            {
                break;
            }
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowActivated

    private void NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoBtnActionPerformed

    private void YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesBtnActionPerformed

    private void YesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesBtnMouseClicked
        // TODO add your handling code here:
        ABloodTypeSelection.setEnabled(false);
        
    }//GEN-LAST:event_YesBtnMouseClicked

    private void YesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_YesBtnMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_YesBtnMouseEntered

    private void NoBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NoBtnKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_NoBtnKeyPressed

    private void NoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoBtnMouseClicked
        // TODO add your handling code here:
        ABloodTypeSelection.setEnabled(true);
    }//GEN-LAST:event_NoBtnMouseClicked

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        // TODO add your handling code here:
        String Rtype= RcatogoryBox.getSelectedItem().toString();
        String RBloodType;
        int count= parseInt(CountSpr.getValue().toString());
        if(YesBtn.isSelected())
        {
            RBloodType=BloodTypeSelection.getSelectedItem().toString();
        }
        else
        {
            RBloodType=ABloodTypeSelection.getSelectedItem().toString();
        }
        String Wno=WnoTxt.getText();
        int Bno=parseInt(BedNoTxt.getText());
        int Age=parseInt(AgeTxt.getText());
        double Weight=Double.parseDouble((WeightTxt.getText()));
        HgetBpacket BP = new HgetBpacket();
        try {
            if(count>BP.getCount(RBloodType) && NoBtn.isSelected())
            {
                Component frame = null;
                JOptionPane.showMessageDialog(frame, "Try Alternative Blood Type");
            }
            else
            {
            BP.InsertData(Rtype, RBloodType, count, Wno, Bno, Age, Weight);
            Component frame = null;
            JOptionPane.showMessageDialog(frame, "Data Entered Successfully");
            rest();
            }
        } catch (SQLException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HGetBP.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void WeightTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WeightTxtKeyPressed
        // TODO add your handling code here:
        if(WnoTxt.getText().isEmpty()||BedNoTxt.getText().isEmpty()||AgeTxt.getText().isEmpty()||WeightTxt.getText().isEmpty())
        {
            SubmitBtn.setEnabled(false);
        }
        else{SubmitBtn.setEnabled(true);}
    }//GEN-LAST:event_WeightTxtKeyPressed

    private void WeightTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WeightTxtKeyTyped
         
    }//GEN-LAST:event_WeightTxtKeyTyped

    private void WeightTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WeightTxtKeyReleased
        validateF(WeightTxt.getText(),"^[1-9]{1}[0-9]{1,3}|[1-9]$",lblValidateWeight); // TODO add your handling code here:
        check();
    }//GEN-LAST:event_WeightTxtKeyReleased

    public void rest()
    {
        WnoTxt.setText("");
        BedNoTxt.setText("");
        AgeTxt.setText("");
        WeightTxt.setText("");
    }
     public void validateF(String text,String pattern,JLabel l1){
        Pattern p=Pattern.compile(pattern);
        Matcher m=p.matcher(text);
        if(m.matches()){
                            l1.setText("Valid input");
                            l1.setForeground(Color.green);
        }else{
                            l1.setText("Invalid input");
                            l1.setForeground(Color.RED);
        }
    }
     public void check(){
        if(lblValidateWardNo.getForeground().equals(Color.green)&lblValidateBedNo.getForeground().equals(Color.green)&lblValidateAge.getForeground().equals(Color.green)&lblValidateWeight.getForeground().equals(Color.green)){
            SubmitBtn.setEnabled(true);
        }else{
            SubmitBtn.setEnabled(false);
        }
    }
     public void addError(){
        lblValidateWardNo.setText(" ");
        lblValidateBedNo.setText(" ");
        lblValidateWeight.setText(" ");
        lblValidateAge.setText(" ");
        lblValidateWardNo.setForeground(Color.red);
        lblValidateBedNo.setForeground(Color.red);
        lblValidateWeight.setForeground(Color.red);
        lblValidateWeight.setForeground(Color.red);
    }
    private void SubmitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_SubmitBtnMouseEntered

    private void AgeTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtKeyPressed

    private void WnoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WnoTxtKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_WnoTxtKeyPressed

    private void BedNoTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BedNoTxtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BedNoTxtKeyPressed

    private void WnoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WnoTxtKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_WnoTxtKeyTyped

    private void BedNoTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BedNoTxtKeyTyped
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BedNoTxtKeyTyped

    private void AgeTxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTxtKeyTyped
        // TODO add your handling code here:
    
    }//GEN-LAST:event_AgeTxtKeyTyped

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        FPage fp = new FPage();
        fp.show();
        dispose();
    }//GEN-LAST:event_BackBtnActionPerformed

    private void WnoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_WnoTxtKeyReleased
       validateF(WnoTxt.getText(),"^[1-9]{1}[0-9]{1,3}|[1-9]$",lblValidateWardNo); // TODO add your handling code here:
       check();        // TODO add your handling code here:
    }//GEN-LAST:event_WnoTxtKeyReleased

    private void BedNoTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BedNoTxtKeyReleased
        validateF(BedNoTxt.getText(),"^[1-9]{1}[0-9]{1,3}|[1-9]$",lblValidateBedNo); // TODO add your handling code here:
        check(); // TODO add your handling code here:
    }//GEN-LAST:event_BedNoTxtKeyReleased

    private void AgeTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_AgeTxtKeyReleased
      validateF(AgeTxt.getText(),"^[1-9]{1}[0-9]{1,3}|[1-9]$",lblValidateAge); // TODO add your handling code here:
      check();  // TODO add your handling code here:
    }//GEN-LAST:event_AgeTxtKeyReleased

    private void ABloodTypeSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABloodTypeSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ABloodTypeSelectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HGetBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HGetBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HGetBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HGetBP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HGetBP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ABloodTypeSelection;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JToggleButton BackBtn;
    private javax.swing.JTextField BedNoTxt;
    private javax.swing.JPanel BgPanel;
    private javax.swing.JComboBox<String> BloodTypeSelection;
    private javax.swing.JSpinner CountSpr;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel LeftPanel;
    private javax.swing.JRadioButton NoBtn;
    private javax.swing.JComboBox<String> RcatogoryBox;
    private javax.swing.JPanel RightPanel;
    private javax.swing.JToggleButton SubmitBtn;
    private javax.swing.JTextField WeightTxt;
    private javax.swing.JTextField WnoTxt;
    private javax.swing.JRadioButton YesBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel containelPanel;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lblValidateAge;
    private javax.swing.JLabel lblValidateBedNo;
    private javax.swing.JLabel lblValidateWardNo;
    private javax.swing.JLabel lblValidateWeight;
    private javax.swing.JPanel rootPanel1;
    // End of variables declaration//GEN-END:variables
}
